apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: ms-project
spec:
  serviceName: nacos-service
  replicas: 1  # 单机模式，后续可扩展
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8848
          name: server
        - containerPort: 9848
          name: client-rpc
        - containerPort: 9849
          name: raft-rpc
        env:
        - name: MODE
          value: "standalone"
        - name: JVM_XMS
          value: "512m"
        - name: JVM_XMX
          value: "512m"
        - name: JVM_XMN
          value: "256m"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: MYSQL_SERVICE_HOST
          value: "nacos-mysql.ms-project.svc.cluster.local"
        - name: MYSQL_SERVICE_DB_NAME
          value: "nacos"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_USER
          valueFrom:
            secretKeyRef:
              name: nacos-mysql-secret
              key: mysql-user
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-mysql-secret
              key: mysql-password
        volumeMounts:
        - name: nacos-data
          mountPath: /home/nacos/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /nacos/actuator/health
            port: 8848
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /nacos/actuator/health
            port: 8848
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: nacos-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: cbs
      resources:
        requests:
          storage: 10Gi