---
# Nacos MySQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: nacos-mysql-secret
  namespace: ms-project
type: Opaque
data:
  mysql-root-password: TmFjb3NfUm9vdF8xMjM0  # Nacos_Root_1234
  mysql-password: TmFjb3NfUGFzcw==          # Nacos_Pass
  mysql-user: bmFjb3M=                      # nacos
---
# Nacos MySQL ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-mysql-config
  namespace: ms-project
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    port=3306
    bind-address=0.0.0.0
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_allowed_packet=16M
    innodb_buffer_pool_size=256M
    innodb_log_file_size=64M
    slow_query_log=1
    slow_query_log_file=/var/lib/mysql/mysql-slow.log
    long_query_time=2
    
    [client]
    default-character-set=utf8mb4
    
    [mysql]
    default-character-set=utf8mb4
---
# Nacos MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql
  namespace: ms-project
spec:
  selector:
    app: nacos-mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None  # Headless Service
---
# Nacos MySQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos-mysql
  namespace: ms-project
spec:
  serviceName: nacos-mysql
  replicas: 1
  selector:
    matchLabels:
      app: nacos-mysql
  template:
    metadata:
      labels:
        app: nacos-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.32
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "nacos"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nacos-mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-mysql-secret
              key: mysql-password
        volumeMounts:
        - name: nacos-mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: nacos-mysql-data
          mountPath: /var/lib/mysql
        - name: nacos-mysql-structure
          mountPath: /docker-entrypoint-initdb.d/nacos-mysql.sql
          subPath: nacos-mysql.sql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "mysqladmin ping -h 127.0.0.1 -P 3306 -u root -p$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "mysqladmin ping -h 127.0.0.1 -P 3306 -u root -p$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: nacos-mysql-config
        configMap:
          name: nacos-mysql-config
      - name: nacos-mysql-structure
        configMap:
          name: nacos-mysql-structure
          items:
          - key: nacos-mysql.sql
            path: nacos-mysql.sql
  volumeClaimTemplates:
  - metadata:
      name: nacos-mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: cbs
      resources:
        requests:
          storage: 10Gi