apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: ms-project
spec:
  serviceName: etcd3
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.7
        command:
        - /usr/local/bin/etcd
        - --name=etcd-0
        - --initial-advertise-peer-urls=http://$(POD_IP):2380
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(POD_IP):2379
        - --initial-cluster-token=etcd-cluster
        - --initial-cluster=etcd-0=http://$(POD_IP):2380
        - --initial-cluster-state=new
        - --data-dir=/var/lib/etcd
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        volumeMounts:
        - name: etcd-data
          mountPath: /var/lib/etcd
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi