server:
  name: "project-api"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "E:\\闭关\\项目\\gin管理系统\\ms_project\\project-api\\log_dir\\debug\\project-debug.log"
  infoFileName: "E:\\闭关\\项目\\gin管理系统\\ms_project\\project-api\\log_dir\\info\\project-info.log"
  warnFileName: "E:\\闭关\\项目\\gin管理系统\\ms_project\\project-api\\log_dir\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"
minIO:
  endpoint: "127.0.0.1:9009"
  accessKey: "zhjO0PcMeLCNxMJby6bu"
  secretKey: "1iy3ZYOOwQaKAumkxkm0Utma5TpF6rZrYyEgKHoA"
  useSSL: false
  bucket: "ms-project"
