apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-project
  namespace: ms-project
  labels:
    app: project-project
spec:
  selector:
    matchLabels:
      app: project-project
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: project-project
    spec:
      imagePullSecrets:
        - name: tencent-ccr-secret
      containers:
        - image: hkccr.ccs.tencentyun.com/ms-project/project-project:v1.0.3
          name: project-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8882
              protocol: TCP
          volumeMounts:
          - name: project-config
            mountPath: /app/config/app.yaml
            subPath: app.yaml
          - name: project-nacos-config
            mountPath: /app/config/nacos_config.yaml
            subPath: nacos_config.yaml
      volumes:
      - name: project-config
        configMap:
          name: project-project-app-conf
      - name: project-nacos-config
        configMap:
          name: project-project-nacos-conf