apiVersion: v1
kind: ConfigMap
metadata:
  name: project-project-app-conf
  namespace: ms-project
data:
  app.yaml: |-
    server:
      name: "project-project"
      addr: "0.0.0.0:8082"
    zap:
      debugFileName: "/logs/debug/project-debug.log"
      infoFileName: "/logs/info/project-info.log"
      warnFileName: "/logs/error/project-error.log"
      maxSize: 500,
      maxAge: 28,
      MaxBackups: 3
    redis:
      host: "redis-service"
      port: 6379
      password: ""
      db: 0
    grpc:
      listenAddr: "0.0.0.0:8882"
      connectAddr: "project-project:8882"
      name: "project"
      version: "1.0.0"
      weight: 2
    etcd:
      addrs:
        - "etcd3:2379"
    mysql:
      username: "enspire"
      password: "Changeme"
      host: mysql-master
      port: 3306
      db: msproject
    kafka:
      addr: "kafka:9092"
    jaeger:
      collectorAddr: "jaeger:14268"