apiVersion: v1
kind: ConfigMap
metadata:
  name: project-project-nacos-conf
  namespace: ms-project
data:
  nacos_config.yaml: |-
    nacos:
      namespaceId: 4a637275-54c7-455a-b590-631bac6fcef2
      group: dev
      ipAddr: nacos-service
      port: 8848
      scheme: http
      contextPath: "/nacos"