kind: Service
apiVersion: v1
metadata:
  name: es
  namespace: ms-project
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: http
    targetPort: 9200
  - port: 9300
    name: transport
    targetPort: 9300