// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: project_service.proto

package project

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	Index(ctx context.Context, in *IndexMessage, opts ...grpc.CallOption) (*IndexResponse, error)
	GetProjectList(ctx context.Context, in *GetProjectListReq, opts ...grpc.CallOption) (*GetProjectListResp, error)
	GetProjectTemplates(ctx context.Context, in *GetProjectTemplatesReq, opts ...grpc.CallOption) (*GetProjectTemplatesResp, error)
	SaveProject(ctx context.Context, in *SaveProjectReq, opts ...grpc.CallOption) (*SaveProjectResp, error)
	GetProjectDetail(ctx context.Context, in *GetProjectDetailReq, opts ...grpc.CallOption) (*GetProjectDetailResp, error)
	CollectProject(ctx context.Context, in *CollectProjectReq, opts ...grpc.CallOption) (*CollectProjectResp, error)
	UpdateProjectDeletedState(ctx context.Context, in *UpdateProjectDeletedStateReq, opts ...grpc.CallOption) (*UpdateProjectDeletedStateResp, error)
	UpdateProject(ctx context.Context, in *UpdateProjectReq, opts ...grpc.CallOption) (*UpdateProjectResp, error)
	GetProjectMemberList(ctx context.Context, in *GetProjectMemberListReq, opts ...grpc.CallOption) (*GetProjectMemberListResp, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Index(ctx context.Context, in *IndexMessage, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectList(ctx context.Context, in *GetProjectListReq, opts ...grpc.CallOption) (*GetProjectListResp, error) {
	out := new(GetProjectListResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/GetProjectList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectTemplates(ctx context.Context, in *GetProjectTemplatesReq, opts ...grpc.CallOption) (*GetProjectTemplatesResp, error) {
	out := new(GetProjectTemplatesResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/GetProjectTemplates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SaveProject(ctx context.Context, in *SaveProjectReq, opts ...grpc.CallOption) (*SaveProjectResp, error) {
	out := new(SaveProjectResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/SaveProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectDetail(ctx context.Context, in *GetProjectDetailReq, opts ...grpc.CallOption) (*GetProjectDetailResp, error) {
	out := new(GetProjectDetailResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/GetProjectDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CollectProject(ctx context.Context, in *CollectProjectReq, opts ...grpc.CallOption) (*CollectProjectResp, error) {
	out := new(CollectProjectResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/CollectProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProjectDeletedState(ctx context.Context, in *UpdateProjectDeletedStateReq, opts ...grpc.CallOption) (*UpdateProjectDeletedStateResp, error) {
	out := new(UpdateProjectDeletedStateResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/UpdateProjectDeletedState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectReq, opts ...grpc.CallOption) (*UpdateProjectResp, error) {
	out := new(UpdateProjectResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/UpdateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectMemberList(ctx context.Context, in *GetProjectMemberListReq, opts ...grpc.CallOption) (*GetProjectMemberListResp, error) {
	out := new(GetProjectMemberListResp)
	err := c.cc.Invoke(ctx, "/project.service.v1.ProjectService/GetProjectMemberList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility
type ProjectServiceServer interface {
	Index(context.Context, *IndexMessage) (*IndexResponse, error)
	GetProjectList(context.Context, *GetProjectListReq) (*GetProjectListResp, error)
	GetProjectTemplates(context.Context, *GetProjectTemplatesReq) (*GetProjectTemplatesResp, error)
	SaveProject(context.Context, *SaveProjectReq) (*SaveProjectResp, error)
	GetProjectDetail(context.Context, *GetProjectDetailReq) (*GetProjectDetailResp, error)
	CollectProject(context.Context, *CollectProjectReq) (*CollectProjectResp, error)
	UpdateProjectDeletedState(context.Context, *UpdateProjectDeletedStateReq) (*UpdateProjectDeletedStateResp, error)
	UpdateProject(context.Context, *UpdateProjectReq) (*UpdateProjectResp, error)
	GetProjectMemberList(context.Context, *GetProjectMemberListReq) (*GetProjectMemberListResp, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (UnimplementedProjectServiceServer) Index(context.Context, *IndexMessage) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectList(context.Context, *GetProjectListReq) (*GetProjectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectList not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectTemplates(context.Context, *GetProjectTemplatesReq) (*GetProjectTemplatesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectTemplates not implemented")
}
func (UnimplementedProjectServiceServer) SaveProject(context.Context, *SaveProjectReq) (*SaveProjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectDetail(context.Context, *GetProjectDetailReq) (*GetProjectDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectDetail not implemented")
}
func (UnimplementedProjectServiceServer) CollectProject(context.Context, *CollectProjectReq) (*CollectProjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectProject not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProjectDeletedState(context.Context, *UpdateProjectDeletedStateReq) (*UpdateProjectDeletedStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectDeletedState not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProject(context.Context, *UpdateProjectReq) (*UpdateProjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectMemberList(context.Context, *GetProjectMemberListReq) (*GetProjectMemberListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectMemberList not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Index(ctx, req.(*IndexMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/GetProjectList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectList(ctx, req.(*GetProjectListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectTemplatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/GetProjectTemplates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectTemplates(ctx, req.(*GetProjectTemplatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SaveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SaveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/SaveProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SaveProject(ctx, req.(*SaveProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/GetProjectDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectDetail(ctx, req.(*GetProjectDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CollectProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CollectProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/CollectProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CollectProject(ctx, req.(*CollectProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProjectDeletedState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectDeletedStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProjectDeletedState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/UpdateProjectDeletedState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProjectDeletedState(ctx, req.(*UpdateProjectDeletedStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProject(ctx, req.(*UpdateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectMemberListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.service.v1.ProjectService/GetProjectMemberList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectMemberList(ctx, req.(*GetProjectMemberListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.service.v1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _ProjectService_Index_Handler,
		},
		{
			MethodName: "GetProjectList",
			Handler:    _ProjectService_GetProjectList_Handler,
		},
		{
			MethodName: "GetProjectTemplates",
			Handler:    _ProjectService_GetProjectTemplates_Handler,
		},
		{
			MethodName: "SaveProject",
			Handler:    _ProjectService_SaveProject_Handler,
		},
		{
			MethodName: "GetProjectDetail",
			Handler:    _ProjectService_GetProjectDetail_Handler,
		},
		{
			MethodName: "CollectProject",
			Handler:    _ProjectService_CollectProject_Handler,
		},
		{
			MethodName: "UpdateProjectDeletedState",
			Handler:    _ProjectService_UpdateProjectDeletedState_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProjectService_UpdateProject_Handler,
		},
		{
			MethodName: "GetProjectMemberList",
			Handler:    _ProjectService_GetProjectMemberList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project_service.proto",
}
