server:
  name: "project-user"
  addr: "project-user:8080"
zap:
  debugFileName: "/logs/debug/project-debug.log"
  infoFileName: "/logs/info/project-info.log"
  warnFileName: "/logs/error/project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "redis6"
  port: 6379
  password: ""
  db: 0
grpc:
  listenAddr: "project-user:8881"
  connectAddr: "project-user:8881"
  name: "login"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"
mysql:
  username: root
  password: root
  host: mysql8
  port: 3306
  db: msproject
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: msproject
  refreshSecret: ms_project
jaeger:
  collectorAddr: "jaeger:14268"