# headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ms-project
spec:
  clusterIP: None  # Headless Service
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis