server:
  name: "project-project"
  addr: "127.0.0.1:8082"
zap:
  debugFileName: "E:\\闭关\\项目\\gin管理系统\\ms_project\\project-project\\log_dir\\debug\\project-debug.log"
  infoFileName: "E:\\闭关\\项目\\gin管理系统\\ms_project\\project-project\\log_dir\\info\\project-info.log"
  warnFileName: "E:\\闭关\\项目\\gin管理系统\\ms_project\\project-project\\log_dir\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8882"
  name: "project"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  master:
    username: root
    password: Test_1234
    host: 127.0.0.1
    port: 3306
    db: msproject
  slaveList:
    - username: root
      password: Test_1234
      host: 127.0.0.1
      port: 3306
      db: msproject_slave
    - username: root
      password: Test_1234
      host: 127.0.0.1
      port: 3306
      db: msproject_slave2