kind: Service
apiVersion: v1
metadata:
  name: jaeger
  namespace: ms-project
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
  - port: 16686
    name: jaegerservice
    targetPort: 16686
    nodePort: 31093
  - port: 14268
    name: service
    targetPort: 14268