apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-yml
  namespace: ms-project
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: http://es:9200
    xpack.monitoring.enabled: true