apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: ms-project
  labels:
    app: kibana
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.17.9
        imagePullPolicy: Always
        ports:
        - containerPort: 5601
        env:
        - name: SERVER_NAME
          value: "kibana"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: ELASTICSEARCH_HOSTS
          value: "http://es:9200"