kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: ms-project
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - port: 5601
    name: kibana
    targetPort: 5601
    nodePort: 31095