apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  namespace: ms-project
data:
  my.cnf: |
    [mysqld]
    server-id=1
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default_authentication_plugin=mysql_native_password
    max_connections=1000
    innodb_buffer_pool_size=256M
    explicit_defaults_for_timestamp=true
    lower_case_table_names=1
    log-bin=mysql-bin
    binlog_format=ROW
    binlog_do_db=msproject
    binlog_ignore_db=mysql
    binlog_ignore_db=information_schema
    binlog_ignore_db=performance_schema
    binlog_ignore_db=sys