apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: ms-project
spec:
  selector:
    app: mysql-master
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: ms-project
spec:
  selector:
    app: mysql-slave
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
  clusterIP: None
