apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
  namespace: ms-project
data:
  my.cnf: |
    [mysqld]
    server-id=2
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default_authentication_plugin=mysql_native_password
    max_connections=1000
    innodb_buffer_pool_size=256M
    explicit_defaults_for_timestamp=true
    lower_case_table_names=1
    relay-log=mysql-relay-bin
    read_only=1
    replicate_do_db=msproject
    replicate_ignore_db=mysql
    replicate_ignore_db=information_schema
    replicate_ignore_db=performance_schema
    replicate_ignore_db=sys