kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: ms-project
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9000
    name: api
    targetPort: 9000
    nodePort: 31097
  - port: 9001
    name: console
    targetPort: 9001
    nodePort: 31098