apiVersion: v1
kind: Service
metadata:
  name: project-api
  namespace: ms-project
  labels:
    app: project-api
spec:
  selector:
    app: project-api
  ports:
    - name: project-api-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080
  type: NodePort