package model

import (
	"test.com/project-common/errs"
)

var (
	GetAllMenusError               = errs.NewError(2000, "获取菜单出错")
	GetProjectListError            = errs.NewError(2001, "获取项目列表出错")
	InvalidViewType                = errs.NewError(2002, "错误的view类型")
	QueryProjectTemplateError      = errs.NewError(2003, "查询项目模板出错")
	QueryTemplateTaskStagesError   = errs.NewError(2004, "查询模板任务步骤出错")
	SaveProjectError               = errs.NewError(2005, "保存项目出错")
	SaveProjectMembertError        = errs.NewError(2006, "保存项目成员出错")
	EncryptProjectIdError          = errs.NewError(2007, "对项目id加密出错")
	EncryptOrganizationIdError     = errs.NewError(2008, "对项目id加密出错")
	GetOrganizationError           = errs.NewError(2009, "获取组织信息出错")
	GetProjectAndMemberError       = errs.NewError(2010, "获取项目和成员信息出错")
	GetMemberByIdError             = errs.NewError(2011, "根据id获取成员信息出错")
	GetProjectCollectedStateError  = errs.NewError(2012, "获取项目收藏状态出错")
	DecryptProjectCodeError        = errs.NewError(2013, "解密项目编码出错")
	ParseProjectIdError            = errs.NewError(2014, "解析项目ID出错")
	CollectProjectError            = errs.NewError(2015, "收藏项目出错")
	CancelCollectProjectError      = errs.NewError(2016, "取消收藏项目出错")
	InvalidCollectType             = errs.NewError(2017, "无效的收藏类型")
	UpdateProjectDeletedStateError = errs.NewError(2018, "更新项目删除状态出错")
	UpdateProjectError             = errs.NewError(2019, "更新项目出错")
	GetTaskStagesError             = errs.NewError(2020, "获取任务步骤出错")
	CopyTaskStageListError         = errs.NewError(2021, "复制任务步骤列表出错")
	EncryptTaskStageIdError        = errs.NewError(2022, "加密任务步骤id出错")
	TemplateTaskStagesNotFound     = errs.NewError(2023, "模板任务步骤不存在")
	SaveTaskStageError             = errs.NewError(2024, "保存任务步骤出错")
	GetProjectMemberListError      = errs.NewError(2025, "获取项目成员列表出错")
	GetMembersInfoError            = errs.NewError(2026, "获取成员信息出错")
	TaskStageCodeError             = errs.NewError(2027, "任务步骤编码错误")
	GetTasksByStageCodeError       = errs.NewError(2028, "根据任务步骤编码获取任务列表出错")
	GetTaskMembersError            = errs.NewError(2029, "获取任务成员列表出错")
	TaskStageNotExistError         = errs.NewError(2030, "任务步骤不存在")
	ProjectNotExistError           = errs.NewError(2031, "项目不存在")
	ProjectDeletedError            = errs.NewError(2032, "项目已删除")
	GetMaxIdNumError               = errs.NewError(2033, "获取任务表中id_num字段最大值出错")
	GetMaxSortError                = errs.NewError(2034, "获取任务表中sort字段最大值出错")
	SaveTaskError                  = errs.NewError(2035, "保存任务出错")
	SaveTaskMemberError            = errs.NewError(2036, "保存任务成员出错")
	GetTaskError                   = errs.NewError(2037, "获取任务出错")
	ModifyStageCodeError           = errs.NewError(2038, "更新任务步骤编码出错")
	GetTaskSortError               = errs.NewError(2039, "获取任务sort出错")
	IncreaseSortError              = errs.NewError(2040, "增加任务sort出错")
	ModifyTaskSortError            = errs.NewError(2040, "修改任务sort出错")
	GetTaskStageError              = errs.NewError(2041, "获取任务步骤出错")
	GetTaskListError               = errs.NewError(2042, "获取任务列表出错")
	InvalidTaskType                = errs.NewError(2043, "无效的任务类型")
	GetProjectsInfoError           = errs.NewError(2044, "获取项目信息出错")
	GetProjectError                = errs.NewError(2045, "获取项目出错")
	CreateProjectLogError          = errs.NewError(2046, "创建项目日志出错")
	GetProjectLogListError         = errs.NewError(2047, "获取项目日志列表出错")
	SaveTaskWorkTimeError          = errs.NewError(2048, "保存任务工时出错")
	GetTaskWorkTimeListError       = errs.NewError(2049, "获取任务工时列表出错")
	SaveFileError                  = errs.NewError(2050, "保存文件记录出错")
	SaveSourceLinkError            = errs.NewError(2051, "保存资源关联记录出错")
	GetSourceLinkListError         = errs.NewError(2052, "获取资源关联列表出错")
	GetFileListByIdsError          = errs.NewError(2053, "根据文件id列表获取文件列表出错")
	GetIdToMemberMapError          = errs.NewError(2054, "获取id到成员映射出错")
	GetProjectAuthListError        = errs.NewError(2055, "获取项目权限列表出错")
	GetMemberAccountListError      = errs.NewError(2056, "获取成员账号列表出错")
	GetDepartmentByIdError         = errs.NewError(2057, "获取部门信息出错")
	GetOrganizationListError       = errs.NewError(2058, "获取组织列表出错")
	GetDepartmentListError         = errs.NewError(2059, "获取部门列表出错")
	DecryptError                   = errs.NewError(2060, "解密出错")
	SearchDepartmentListError      = errs.NewError(2061, "搜索部门列表出错")
	AddDepartmentError             = errs.NewError(2062, "添加部门出错")
	GetProjectNodeListError        = errs.NewError(2063, "获取项目节点列表出错")
	GetProjectAuthNodeListError    = errs.NewError(2064, "获取项目权限节点列表出错")
	InvalidActionType              = errs.NewError(2065, "无效的action类型")
	DeleteProjectAuthNodeError     = errs.NewError(2066, "删除项目权限节点出错")
	AddProjectAuthNodeError        = errs.NewError(2067, "添加项目权限节点出错")
	GetMemberAccountError          = errs.NewError(2068, "获取成员账号出错")
	ParseAuthIdError               = errs.NewError(2069, "解析权限id出错")
	ParseTaskIdError               = errs.NewError(2070, "解析任务id出错")
	InvalidProjectCodeOrTaskCode   = errs.NewError(2071, "无效的项目编码或任务编码")
	GetProjectCodeByTaskIdError    = errs.NewError(2072, "根据任务id获取项目编码出错")
)
