package model

import (
	"test.com/project-common/errs"
)

var (
	GetAllMenusError               = errs.NewError(2000, "获取菜单出错")
	GetProjectListError            = errs.NewError(2001, "获取项目列表出错")
	InvalidViewType                = errs.NewError(2002, "错误的view类型")
	QueryProjectTemplateError      = errs.NewError(2003, "查询项目模板出错")
	QueryTemplateTaskStagesError   = errs.NewError(2004, "查询模板任务步骤出错")
	SaveProjectError               = errs.NewError(2005, "保存项目出错")
	SaveProjectMembertError        = errs.NewError(2006, "保存项目成员出错")
	EncryptProjectIdError          = errs.NewError(2007, "对项目id加密出错")
	EncryptOrganizationIdError     = errs.NewError(2008, "对项目id加密出错")
	GetOrganizationError           = errs.NewError(2009, "获取组织信息出错")
	GetProjectAndMemberError       = errs.NewError(2010, "获取项目和成员信息出错")
	GetMemberByIdError             = errs.NewError(2011, "根据id获取成员信息出错")
	GetProjectCollectedStateError  = errs.NewError(2012, "获取项目收藏状态出错")
	DecryptProjectCodeError        = errs.NewError(2013, "解密项目编码出错")
	ParseProjectIdError            = errs.NewError(2014, "解析项目ID出错")
	CollectProjectError            = errs.NewError(2015, "收藏项目出错")
	CancelCollectProjectError      = errs.NewError(2016, "取消收藏项目出错")
	InvalidCollectType             = errs.NewError(2017, "无效的收藏类型")
	UpdateProjectDeletedStateError = errs.NewError(2018, "更新项目删除状态出错")
	UpdateProjectError             = errs.NewError(2019, "更新项目出错")
	GetTaskStagesError             = errs.NewError(2020, "获取任务步骤出错")
	CopyTaskStageListError         = errs.NewError(2021, "复制任务步骤列表出错")
	EncryptTaskStageIdError        = errs.NewError(2022, "加密任务步骤id出错")
	TemplateTaskStagesNotFound     = errs.NewError(2023, "模板任务步骤不存在")
	SaveTaskStageError             = errs.NewError(2024, "保存任务步骤出错")
	GetProjectMemberListError      = errs.NewError(2025, "获取项目成员列表出错")
	GetMembersInfoError            = errs.NewError(2026, "获取成员信息出错")
	TaskStageCodeError             = errs.NewError(2027, "任务步骤编码错误")
	GetTasksByStageCodeError       = errs.NewError(2028, "根据任务步骤编码获取任务列表出错")
	GetTaskMembersError            = errs.NewError(2029, "获取任务成员列表出错")
	TaskStageNotExistError         = errs.NewError(2030, "任务步骤不存在")
	ProjectNotExistError           = errs.NewError(2031, "项目不存在")
	ProjectDeletedError            = errs.NewError(2032, "项目已删除")
	GetMaxIdNumError               = errs.NewError(2033, "获取任务表中id_num字段最大值出错")
	GetMaxSortError                = errs.NewError(2034, "获取任务表中sort字段最大值出错")
	SaveTaskError                  = errs.NewError(2035, "保存任务出错")
	SaveTaskMemberError            = errs.NewError(2036, "保存任务成员出错")
	GetTaskError                   = errs.NewError(2037, "获取任务出错")
	ModifyStageCodeError           = errs.NewError(2038, "更新任务步骤编码出错")
	GetTaskSortError               = errs.NewError(2039, "获取任务sort出错")
	IncreaseSortError              = errs.NewError(2040, "增加任务sort出错")
	ModifyTaskSortError            = errs.NewError(2040, "修改任务sort出错")
	GetTaskStageError              = errs.NewError(2041, "获取任务步骤出错")
	GetTaskListError               = errs.NewError(2042, "获取任务列表出错")
	InvalidTaskType                = errs.NewError(2043, "无效的任务类型")
	GetProjectsInfoError           = errs.NewError(2044, "获取项目信息出错")
	GetProjectError                = errs.NewError(2045, "获取项目出错")
	CreateProjectLogError          = errs.NewError(2046, "创建项目日志出错")
	GetProjectLogListError         = errs.NewError(2047, "获取项目日志列表出错")
	SaveTaskWorkTimeError          = errs.NewError(2048, "保存任务工时出错")
	GetTaskWorkTimeListError       = errs.NewError(2049, "获取任务工时列表出错")
	SaveFileError                  = errs.NewError(2050, "保存文件记录出错")
	SaveSourceLinkError            = errs.NewError(2051, "保存资源关联记录出错")
)
