apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: ms-project
  labels:
    app: kafdrop
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: KAFKA_BROKERCONNECT
          value: "kafka:29092"
        - name: JVM_OPTS
          value: "-Xms128M -Xmx256M"  # 增加内存分配
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"