apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: ms-project
  labels:
    app: kafka
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: obsidiandynamics/kafka
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_LISTENERS
          value: "INTERNAL://:29092,EXTERNAL://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka.ms-project.svc.cluster.local:29092,EXTERNAL://kafka.ms-project.svc.cluster.local:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
          value: "6000"
        - name: KAFKA_RESTART_ATTEMPTS
          value: "10"
        - name: KAFKA_RESTART_DELAY
          value: "5"
        - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
          value: "0"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"